//Blogs
export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';
export const FETCH_BLOG_DETAILS = 'FETCH_BLOG_DETAILS';
export const FETCH_BLOG_DETAILS_SUCCESS = 'FETCH_BLOG_DETAILS_SUCCESS';
export const FETCH_BLOG_DETAILS_ERROR = 'FETCH_BLOG_DETAILS_ERROR';

//Fetch Home Screen rows

//FETCH_NETFLIX_ORIGINALS
export const FETCH_NETFLIX_ORIGINALS = 'FETCH_NETFLIX_ORIGINALS';
export const FETCH_NETFLIX_ORIGINALS_SUCCESS =
  'FETCH_NETFLIX_ORIGINALS_SUCCESS';
export const FETCH_NETFLIX_ORIGINALS_ERROR = 'FETCH_NETFLIX_ORIGINALS_ERROR';
