//Blogs
export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';
export const FETCH_BLOG_DETAILS = 'FETCH_BLOG_DETAILS';
export const FETCH_BLOG_DETAILS_SUCCESS = 'FETCH_BLOG_DETAILS_SUCCESS';
export const FETCH_BLOG_DETAILS_ERROR = 'FETCH_BLOG_DETAILS_ERROR';
