//Blogs
export const FETCH_BLOGS = 'FETCH_BLOGS';
export const FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS';
export const FETCH_BLOGS_ERROR = 'FETCH_BLOGS_ERROR';
export const FETCH_BLOG_DETAILS = 'FETCH_BLOG_DETAILS';
export const FETCH_BLOG_DETAILS_SUCCESS = 'FETCH_BLOG_DETAILS_SUCCESS';
export const FETCH_BLOG_DETAILS_ERROR = 'FETCH_BLOG_DETAILS_ERROR';

//Fetch Home Screen rows

//FETCH_NETFLIX_ORIGINALS
export const FETCH_NETFLIX_ORIGINALS = 'FETCH_NETFLIX_ORIGINALS';
export const FETCH_NETFLIX_ORIGINALS_SUCCESS =
  'FETCH_NETFLIX_ORIGINALS_SUCCESS';
export const FETCH_NETFLIX_ORIGINALS_ERROR = 'FETCH_NETFLIX_ORIGINALS_ERROR';

//FETCH_NETFLIX_TRENDING
export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';
export const FETCH_TRENDING_MOVIES_SUCCESS = 'FETCH_TRENDING_MOVIES_SUCCESS';
export const FETCH_TRENDING_MOVIES_ERROR = 'FETCH_TRENDING_MOVIES_ERROR';

//FETCH_TOP_RATED
export const FETCH_TOP_RATED = 'FETCH_TOP_RATED';
export const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
export const FETCH_TOP_RATED_ERROR = 'FETCH_TOP_RATED_ERROR';

//FETCH_ACTION_MOVIES
export const FETCH_ACTION_MOVIES = 'FETCH_ACTION_MOVIES';
export const FETCH_ACTION_MOVIES_SUCCESS = 'FETCH_ACTION_MOVIES_SUCCESS';
export const FETCH_ACTION_MOVIES_ERROR = 'FETCH_ACTION_MOVIES_ERROR';

//FETCH_COMEDY_MOVIES
export const FETCH_COMEDY_MOVIES = 'FETCH_COMEDY_MOVIES';
export const FETCH_COMEDY_MOVIES_SUCCESS = 'FETCH_COMEDY_MOVIES_SUCCESS';
export const FETCH_COMEDY_MOVIES_ERROR = 'FETCH_COMEDY_MOVIES_ERROR';

//FETCH_HORROR_MOVIES
export const FETCH_HORROR_MOVIES = 'FETCH_HORROR_MOVIES';
export const FETCH_HORROR_MOVIES_SUCCESS = 'FETCH_HORROR_MOVIES_SUCCESS';
export const FETCH_HORROR_MOVIES_ERROR = 'FETCH_HORROR_MOVIES_ERROR';

//FETCH_ROMANTIC_MOVIES
export const FETCH_ROMANTIC_MOVIES = 'FETCH_ROMANTIC_MOVIES';
export const FETCH_ROMANTIC_MOVIES_SUCCESS = 'FETCH_ROMANTIC_MOVIES_SUCCESS';
export const FETCH_ROMANTIC_MOVIES_ERROR = 'FETCH_ROMANTIC_MOVIES_ERROR';

//FETCH_DOCUMENTARY_MOVIES
export const FETCH_DOCUMENTARY_MOVIES = 'FETCH_DOCUMENTARY_MOVIES';
export const FETCH_DOCUMENTARY_MOVIES_SUCCESS =
  'FETCH_DOCUMENTARY_MOVIES_SUCCESS';
export const FETCH_DOCUMENTARY_MOVIES_ERROR = 'FETCH_DOCUMENTARY_MOVIES_ERROR';
